sonar.projectKey=node-test
sonar.projectName=node-test
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/*.test.js
sonar.coverage.exclusions=**/*.test.js
sonar.tests=src
sonar.test.inclusions=**/*.test.js
sonar.javascript.coveragePlugin=lcov
sonar.javascript.lcov.reportPaths=coverage/lcov.info;
sonar.host.url=http://localhost:9000
sonar.login=sqp_9ff55e2aa91802d8d3f61a0f5e1ddebcd40c1efd
