sonar.projectKey=go-project

sonar.sources=.;   
sonar.exclusions=**/*_test.go

sonar.tests=.;
sonar.test.inclusions=**/*_test.go
sonar.host.url=http://localhost:9000
sonar.login=sqp_a3ed6596dcc8ba0b3452626a7f81c9d2ec1f71b7
sonar.go.coverage.reportPaths=coverage.out